//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CONTASEntities : DbContext
    {
        public CONTASEntities()
            : base("name=CONTASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tb_asistencia_p> tb_asistencia_p { get; set; }
        public DbSet<tb_categoria_persona_m> tb_categoria_persona_m { get; set; }
        public DbSet<tb_persona_m> tb_persona_m { get; set; }
        public DbSet<tb_usuarios_colegio_m> tb_usuarios_colegio_m { get; set; }
    
        public virtual ObjectResult<sp_personas_que_marcaron_hoy_Result> sp_personas_que_marcaron_hoy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_personas_que_marcaron_hoy_Result>("sp_personas_que_marcaron_hoy");
        }
    }
}
