//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_asistencia_p
    {
        public int id_asistencia { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuarios_colegio { get; set; }
    
        public virtual tb_usuarios_colegio_m tb_usuarios_colegio_m { get; set; }
    }
}
