//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_persona_m
    {
        public tb_persona_m()
        {
            this.tb_usuarios_colegio_m = new HashSet<tb_usuarios_colegio_m>();
        }
    
        public int id_persona { get; set; }
        public string nombre_persona { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string num_documento { get; set; }
    
        public virtual ICollection<tb_usuarios_colegio_m> tb_usuarios_colegio_m { get; set; }
    }
}
