//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios_colegio_m
    {
        public tb_usuarios_colegio_m()
        {
            this.tb_asistencia_p = new HashSet<tb_asistencia_p>();
        }
    
        public int id_usuarios_colegio { get; set; }
        public Nullable<int> id_persona { get; set; }
        public Nullable<int> id_categoria_persona { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual ICollection<tb_asistencia_p> tb_asistencia_p { get; set; }
        public virtual tb_categoria_persona_m tb_categoria_persona_m { get; set; }
        public virtual tb_persona_m tb_persona_m { get; set; }
    }
}
